# Generated by Django 5.0.1 on 2024-02-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999)),
                ('icon_url', models.CharField(max_length=255)),
                ('rich_base_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999)),
                ('icon_url', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('theme_color', models.CharField(max_length=100)),
                ('avatar_pc', models.CharField(max_length=999)),
                ('avatar_mobile', models.CharField(max_length=999)),
                ('attrs', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content_id', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=999)),
                ('icon_url', models.CharField(max_length=255)),
                ('star', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=999)),
                ('rich_text', models.CharField(max_length=999)),
                ('attrs', models.CharField(max_length=999)),
            ],
        ),
    ]
